Update checkXML.yml

diff --git a/.github/workflows/checkXML.yml b/.github/workflows/checkXML.yml
--- a/.github/workflows/checkXML.yml
+++ b/.github/workflows/checkXML.yml
@@ -19,14 +19,21 @@ jobs:
         
     - name: Check for track trending enabled
       run: |
+        filesFound="false"
         for file in $(echo "${{ steps.changed_files.outputs.files }}"); do
           echo "- $file"
-          if grep -i "<trackTrending>false</trackTrending>" $file;
+          if grep -i "<trackTrending>true</trackTrending>" $file;
           then
-            echo "found in $file"
-          else
-            echo "not found in $file"
+            filesFound="true"
+            echo "ERROR --->>> trackTrending enabled in : $file"
           fi
         done
+        if [ $filesFound == "true" ]
+        then
+          echo "Please disable trackTrending from the meta files"
+          exit 1
+        else
+          exit 0
+        fi
                         
       
